import { Type } from "@google/genai";

export interface CardData {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  owner: string;
  status: 'full-pile' | 'my-pile' | 'not-interested';
  isFree?: boolean;
  x: number;
  y: number;
  freeX?: number;
  freeY?: number;
  distance: number; // in km
  category: string;
}

export const MOCK_CARDS: CardData[] = [
  {
    id: '1',
    title: 'Vintage Camera',
    description: 'A classic 35mm film camera in excellent condition. Perfect for enthusiasts.',
    imageUrl: 'https://picsum.photos/seed/camera/300/450?grayscale=1',
    owner: 'Alice',
    status: 'full-pile',
    isFree: false,
    x: 100,
    y: 100,
    distance: 0.5,
    category: 'Electronics',
  },
  {
    id: '2',
    title: 'Leather Journal',
    description: 'Handcrafted leather-bound notebook with recycled paper.',
    imageUrl: 'https://picsum.photos/seed/journal/300/450?grayscale=1',
    owner: 'Bob',
    status: 'full-pile',
    isFree: false,
    x: 300,
    y: 150,
    distance: 1.2,
    category: 'Stationery',
  },
  {
    id: '3',
    title: 'Mechanical Watch',
    description: 'Automatic movement with a skeleton dial. A masterpiece of engineering.',
    imageUrl: 'https://picsum.photos/seed/watch/300/450?grayscale=1',
    owner: 'Charlie',
    status: 'full-pile',
    isFree: false,
    x: 500,
    y: 100,
    distance: 2.5,
    category: 'Accessories',
  },
  {
    id: '4',
    title: 'Succulent Pot',
    description: 'Minimalist ceramic pot with a healthy Echeveria succulent.',
    imageUrl: 'https://picsum.photos/seed/plant/300/450?grayscale=1',
    owner: 'Diana',
    status: 'full-pile',
    isFree: true,
    x: 150,
    y: 400,
    freeX: 200,
    freeY: 200,
    distance: 0.8,
    category: 'Home',
  },
  {
    id: '5',
    title: 'Vinyl Record',
    description: 'Rare first pressing of a jazz classic. Pristine audio quality.',
    imageUrl: 'https://picsum.photos/seed/vinyl/300/450?grayscale=1',
    owner: 'Ethan',
    status: 'full-pile',
    isFree: false,
    x: 400,
    y: 450,
    distance: 3.1,
    category: 'Media',
  },
  {
    id: '6',
    title: 'Fountain Pen',
    description: 'Elegant gold-nibbed pen for a smooth writing experience.',
    imageUrl: 'https://picsum.photos/seed/pen/300/450?grayscale=1',
    owner: 'Fiona',
    status: 'full-pile',
    isFree: true,
    x: 650,
    y: 350,
    freeX: 500,
    freeY: 150,
    distance: 0.3,
    category: 'Stationery',
  },
  {
    id: '7',
    title: 'Coffee Grinder',
    description: 'Manual burr grinder for the perfect morning brew.',
    imageUrl: 'https://picsum.photos/seed/coffee/300/450?grayscale=1',
    owner: 'George',
    status: 'full-pile',
    isFree: false,
    x: 800,
    y: 150,
    distance: 5.0,
    category: 'Home',
  },
  {
    id: '8',
    title: 'Canvas Backpack',
    description: 'Durable and stylish backpack for daily commutes or weekend trips.',
    imageUrl: 'https://picsum.photos/seed/bag/300/450?grayscale=1',
    owner: 'Hannah',
    status: 'full-pile',
    isFree: true,
    x: 850,
    y: 450,
    freeX: 350,
    freeY: 400,
    distance: 1.5,
    category: 'Accessories',
  },
  {
    id: '9',
    title: 'Headphones',
    description: 'Studio-quality over-ear headphones with noise isolation.',
    imageUrl: 'https://picsum.photos/seed/audio/300/450?grayscale=1',
    owner: 'Ian',
    status: 'full-pile',
    isFree: false,
    x: 200,
    y: 700,
    distance: 0.9,
    category: 'Electronics',
  },
  {
    id: '10',
    title: 'Desk Lamp',
    description: 'Adjustable LED lamp with warm and cool light settings.',
    imageUrl: 'https://picsum.photos/seed/lamp/300/450?grayscale=1',
    owner: 'Julia',
    status: 'full-pile',
    isFree: true,
    x: 550,
    y: 750,
    freeX: 600,
    freeY: 500,
    distance: 2.2,
    category: 'Home',
  },
];
